trigger: none 

pool: Telecom_Analyzer

stages:
  - stage: build
    jobs:
      - job: 
        steps:
          - task: NodeTaskRunnerInstaller@0
            inputs:
              nodeVersion: '16'
          - task: Npm@1
            inputs:
              command: 'install'
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'drop'
              publishLocation: 'Container'